### ISSUE TITLE
Authentication use case

### ISSUE THREAD

**Issue by ivan-liljeqvist** [amaurycrickx/recognito#10]
Hi! I want to use recognito for authentication purposes. However, when you try to authenticate a voice recognito doesnt know it just picks a random entry instead of saying "Voice unrecognized" or something.

I know it's expected behaviour but can you make it reject unrecognized voices somehow?

**Comment by amaurycrickx** [comment]
I would think the threshold depends on your use case. A confidence ratio is returned in the results so you can decide where to put the balance between false positives and false negatives.
