### ISSUE TITLE
Involving Android Studio

### ISSUE THREAD

**Issue by hasanalituran** [amaurycrickx/recognito#11]
Hey Amaury,thanks for this magnificent work but I have been trying to add your library to Android Studio for 2 days without any success.If it is possible could you upload a .jar file or create a option to add this library using build.gradle.Thanks in advance.

Best regards.

**Comment by amaurycrickx** [comment]
I'm under the impression this wouldn't work well because Recognito is too sensitive to noise present in the surroundings
