### ISSUE TITLE
Changing recognition strategy ??

### ISSUE THREAD

**Issue by Dhia1991** [amaurycrickx/recognito#17]
Hello, 

I'am glad to find a project in java that treats the problem of  speaker identification.
I tried the app and i think it is a good idea to start from it to build a better results app.
I think this app doesn't support the use of many files for each speaker. For example having 3 different audio files of barrack obama speaking, i would like to use them all to be a reference for future barrack obama voice identification.
Is this feature already implemented in the app or i have to add it by myself.

Thanks.

**Comment by amaurycrickx** [comment]
Hopefully, you found it by yourself in the meantime

This is supported by:
VoicePrint mergeVoiceSample(K userKey, File voiceSampleFile)
