### ISSUE TITLE
Comparsion 1 to 1

### ISSUE THREAD

**Issue by javenosa** [amaurycrickx/recognito#19]
Hi,

There is a way to compare 1 voiceprint vs another with the Recognito code?
Just to do Speaker verification and not Speaker identification as recognito does.

Thanks

**Comment by amaurycrickx** [comment]
It would be very easy to implement, have a look at the code in identify()

Given Recognito is quite sensitive to noise or different recording condition, this is not a use case I've been pushing forward. 

Maybe I shouldn't downplay Recognito's capabilities :-)
