### ISSUE TITLE
Voice Segmentation

### ISSUE THREAD

**Issue by alexbuechel** [amaurycrickx/recognito#20]
Hi there,

Is there a possibility to perform voice segmentation (extract different samples) based on an audio file with two (or more) different voices?

Thanks in advance
Alex

**Comment by amaurycrickx** [comment]
Not out-of-the-box...

I'd suggest having a look at the projects listed here (probably you already know them, but...)
https://en.wikipedia.org/wiki/Speaker_diarisation

Cheers

Amaury
