### ISSUE TITLE
Android Not Support

### ISSUE THREAD

**Issue by sujewan** [amaurycrickx/recognito#9]
Hi amaury,

There are limitation to use this library. Because of javax.sound.sampled.*
Is there any alternative for this package.

Or else How to implement into and Android Project
Please advice Me.

Best  Regards,
Sujewan

**Comment by amaurycrickx** [comment]
I'd consider forking the project and removing all code depending on these packages.
The downside is that you have to provide the converted audio samples yourself.
Also please consider that there is a high chance that the software doesn't meet your expectations due to background noise
